# -*- coding: utf-8 -*-
"""Soyabean_Disease_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yh79DNd6klTTe5k_VIYPK4ZdVEopvKOp
"""

# listing folders inside colab noteboks
!ls "/content/drive/MyDrive/Colab Notebooks"

from google.colab import drive
drive.mount('/content/drive')

dataset_path = '/content/drive/MyDrive/Colab Notebooks/soyabean-disease'

#importing and loading dataset
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = 128
BATCH_SIZE = 32

datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_data = datagen.flow_from_directory(
    dataset_path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_directory(
    dataset_path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

print(train_data.class_indices)

import tensorflow as tf
from tensorflow.keras import layers, models

# Define the model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(2, activation='softmax')  # 2 classes
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=5  # You can increase to 10 later
)

model.save("soyabean_disease_model.h5")

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# Path to test  new image
img_path = '/content/drive/MyDrive/Colab Notebooks/soyabean-disease/Southern Blight/DSC_0049.jpg'

img = image.load_img(img_path, target_size=(IMG_SIZE, IMG_SIZE))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0) / 255.0

# Predict
pred = model.predict(img_array)
class_names = list(train_data.class_indices.keys())

# Show result
plt.imshow(img)
plt.title(f"Prediction: {class_names[np.argmax(pred)]}")
plt.axis('off')
plt.show()

loss, acc = model.evaluate(val_data)
print(f"Validation Accuracy: {acc*100:.2f}%")

!pip install gradio --quiet

import gradio as gr

def predict_disease(img):
    img = img.resize((IMG_SIZE, IMG_SIZE))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    pred = model.predict(img_array)
    class_names = list(train_data.class_indices.keys())
    return class_names[np.argmax(pred)]

gr.Interface(fn=predict_disease,
             inputs=gr.Image(type="pil"),
             outputs="text",
             title="Soyabean Leaf Disease Detector").launch( )